name: amalgamate-check

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEV_DEV=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Amalgamate Check
      run: |
        if ! git diff --exit-code ev.h; then
          echo "ev.h is not sync with source code."
          exit 1
        fi
        if ! git diff --exit-code ev.c; then
          echo "ev.c is not sync with source code."
          exit 1
        fi
