# This is a basic workflow to help you get started with Actions

name: doxygen

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Build documents
      - name: Build documents
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          doxyfile-path: 'docs/Doxyfile'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: doxygen_html
          path: docs/html/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    steps:
      # Deploy to github gh-pages
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: doxygen_html
          path: docs/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          force_orphan: true
